### ISSUE TITLE
Add Automapper!!

### ISSUE THREAD

**Issue by Itzamna-globant** [guillermomunozglobant/ApiMemeGenerator#15]
In the folder Entities you only have the Meme entity and in the Models folder you have the Imagen model and in your Db Context you are registering both as dbsets!!

Move the class Imagen to the Entities Folder!! 

When creating a meme you should return a json object with the info of the newly created meme, at least you should return the creation date and the path to where the meme was created (you can also return the name of the meme and the text that was added)

You are not going to directly return the Meme entity to the user, after creating it you should return the json object mentioned earlier and to avoid mapping every property by hand you need to use automapper.
https://automapper.org/

**Comment by guillermomunozglobant** [comment]
Adding automapper #23
